#!/bin/bash
echo Downloading lots data from google docs...
wget --output-document=./lots-data.csv "https://docs.google.com/spreadsheets/d/1bHj5bwDiML3oCjRILC8JbApxIxQWMxAu3ZJenxtEShs/export?format=csv"

echo
echo Converting lots data to JSON format...
./csv2json ./lots-data.csv > ./js/lots-data.js

echo ./lots-data.csv  TO  ./js/lots-data.js
rm -v ./lots-data.csv

echo
echo Running Jekyll build...
jekyll build

echo
echo Packaging web site into zip-file...
./package

if [ -f ~/desktop/parking-site.zip ]
  then
    echo
    echo Deleting old parking site zip file...
    rm -v ~/desktop/parking-site.zip
fi
cp ./_build/parking-site.zip ~/desktop/parking-site.zip
